add clearer distinction of setup between languages + fail safe when stuff not installed

diff --git a/dot/zshrc b/dot/zshrc
--- a/dot/zshrc
+++ b/dot/zshrc
@@ -88,21 +88,45 @@ export PATH="$HOME/flutter/bin:$PATH"
 export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
 export ANDROID_HOME="$HOME/Library/Android/sdk"
 
-# Python (pyenv + Poetry setup)
-eval "$(pyenv init -)"
+# # # # # # # # # # # # # # 
+# P y t h o n
+# # # # # # # # # # # # # #
+
+# Check if pyenv is installed
+if ! command -v pyenv &> /dev/null
+then
+  echo "pyenv could not be found"
+else
+  eval "$(pyenv init -)"
+fi
+
 export PATH="$HOME/.poetry/bin:$PATH"
 export PYTHONDONTWRITEBYTECODE=1
 
-# Go setup
+# # # # # # # # # # # # # # 
+# G o l a n g
+# # # # # # # # # # # # # #
+
 export GOPATH=$HOME/go
 export GOBIN=$GOPATH/bin
 export PATH="$GOBIN":$PATH
 
-# Ruby setup
-export PATH="$HOME/.rbenv/bin:$PATH"
-eval "$(rbenv init -)"
+# # # # # # # # # # # # # # 
+# R u b y 
+# # # # # # # # # # # # # #
 
-# Rust setup
+# Check if rbenv is installed
+if ! command -v rbenv &> /dev/null
+then
+  echo "rbenv could not be found"
+else
+  eval "$(rbenv init -)"
+  export PATH="$HOME/.rbenv/bin:$PATH"
+fi
+
+# # # # # # # # # # # # # # 
+# R u s t 
+# # # # # # # # # # # # # #
 export PATH="$HOME/.cargo/bin:$PATH"
 
 # nvm configuration
